name: Build Packages

on:
  push:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/library/archlinux:latest
    strategy:
        matrix:
          arch: ['x86_64']
    steps:
    - name: Cache pacman packages
      id: cache-pacman
      uses: actions/cache@v4
      with:
        path: /var/cache/pacman/pkg
        key: ${{ runner.os }}-pacman-${{ github.sha }}
        restore-keys: ${{ runner.os }}-pacman-

    - name: Set up build environment
      run: |
        pacman-key --init
        pacman-key --populate archlinux
        pacman -Syu --noconfirm base-devel git
        echo 'MAKEFLAGS="--jobs=$(nproc)"' >> /etc/makepkg.conf
        useradd -m builder
        echo 'builder ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder
        sudo -u builder mkdir -pv /tmp/pkgs
        sudo -u builder git clone --depth 1 https://github.com/LingmoOS/aur /tmp/aur
        for i in modemmanager-qt5;do
          sudo -u builder git clone --depth 1 https://aur.archlinux.org/$i.git /tmp/$i
          pushd /tmp/$i
            sudo -u builder makepkg -csi --noconfirm --skippgpcheck
            cp *.pkg.tar.zst /tmp/pkgs
          popd
        done

    - name: Build Packages
      run: |
        cd /tmp/aur
        packages=($(ls -dU lingmoui *))
        packages=($(echo "${packages[@]}" | tr ' ' '\n' | awk '!seen[$0]++'))
        for i in "${packages[@]}";do
          [ -d $i ] && (pushd $i
            sudo -u builder makepkg -csi --noconfirm;cp *.pkg.tar.zst /tmp/pkgs
          popd)
        done
        rm /tmp/pkgs/*-debug-*.pkg.tar.zst
        true

    - name: List Packages
      run: ls -lh /tmp/pkgs

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.arch }}
        compression-level: 0
        path: /tmp/pkgs/*
